### ISSUE TITLE
Does not properly match text. 

### ISSUE THREAD

**Issue by Skamba** [vivami/SauronEye#2]
When looking for pass*, it hits on the document below. I expect that it hits on the word 'pasta', although that has 1 less s than what should be needed to get a hit. 

[brazilian.txt](https://github.com/vivami/SauronEye/files/3884018/brazilian.txt)
![image](https://user-images.githubusercontent.com/8420201/69499878-debea080-0ef6-11ea-8f4a-a263c5657b10.png)
![image](https://user-images.githubusercontent.com/8420201/69499882-e54d1800-0ef6-11ea-9179-7509dbbf15e0.png)

**Comment by vivami** [comment]
I was a bit confused about this at first as well (also because I'm a bit of a regex noob), but this appears to be the correct behaviour: 

> The Match-zero-or-more Operator (*)
>
> This operator repeats the smallest possible preceding regular expression as many times as necessary (including zero) to match the pattern. `*` represents this operator. For example, `o*` matches any string made up of zero or more `o`s. Since this operator operates on the smallest preceding regular expression, `fo*` has a repeating `o`, not a repeating `fo`. So, `fo*` matches `f`, `fo`, `foo`, and so on.  
[Source](http://web.mit.edu/gnu/doc/html/regex_3.html)

Using just `pass` as an argument for the `-Keywords` in SauronEye is sufficient to match on words containing `pass`. No `*`'s needed.
